### PR TITLE
add abstraction layer into redis client

### PR DESCRIPTION
**Pull request by veelasky**
Add abstraction layer into redis client, so the developers can bring their own client configuration.

### CODE REVIEW

**Comment by palicao** [comment]
Thanks @veelasky, this makes a lot of sense, but you should fix tests to be able to get this feature merged!

**Comment by veelasky** [comment]
@palicao actually all tests are passed, but somehow the code exited with code 1, is there anything to add in phpunit.xml config ?

**Comment by palicao** [comment]
> @palicao actually all tests are passed, but somehow the code exited with code 1, is there anything to add in phpunit.xml config ?

Yes, i noticed, and that's why I deleted my previous comment!
I think the problem is that scrutinizer decided to update PHP version to 7.3, and in this version apparently xdebug is not active, so no code coverage can be calculated.

I had a similar problem in another project, so I explicitly required php 7.2 to be installed. Can you please check this `.scrutinizer` file? https://github.com/palicao/phpRebloom/blob/master/.scrutinizer.yml and apply the needed changes? Basically it's about adding 

```
environment:
  php:
    version: 7.2
```

in each node.

Or if you prefer I can try to fix it but you'll need to wait at least tomorrow.

**Comment by veelasky** [comment]
I should add that this is PR is a breaking changes, you should consider move it to different branch, or release all new version all together.

**Comment by palicao** [comment]
@veelasky I think the problem with scrutinizer is even bigger than I thought. I am very sorry for that. I will try to fix it ASAP and come back to this PR.

**Pull request closed without merging**
