### PR TITLE
Return raw results for multiRange

### PR DESCRIPTION
**Pull request by Mrkisha**
As a developer I'd like to be able to map timeseries results into different objects from raw results.

### CODE REVIEW

**Comment by palicao** [comment]
Why don't you map the returned Sample[] to whatever other object you want? For me it's natural that if I need a `Sample` when I `add` something, I will get `Sample`s when I fetch something!
Maybe if you can make an example of your use case, I can understand a bit better what you want to achieve.

**Comment by Mrkisha** [comment]
Data gets lost from raw results to `Sample` results. And I need that data as well.

**Comment by palicao** [comment]
Sorry if I keep asking, but what data exactly gets lost?

**Comment by palicao** [comment]
Ah, got it, I guess you miss labels, right?
Cool, I can merge that, but I would kindly ask you to add tests.

**Comment by Mrkisha** [comment]
Yes, labels are missing.

I'll fix tests later tonight.

Thanks for understanding.

**Comment by Mrkisha** [comment]
I've added tests. @palicao please do the review.

**Review by palicao — APPROVED** [review]

**Comment by palicao** [comment]
Please @Mrkisha update your composer.json to use version 1.1.0!

**Pull request merged**
