### PR TITLE
fix bug found by Mrkisha when passing multiple filters to several methods

### PR DESCRIPTION
**Pull request by palicao**

### CODE REVIEW

**Comment by palicao** [comment]
@Mrkisha can you please take a look? This should solve the "multiple filters" bug in the whole library

**Review by Mrkisha — APPROVED** [review]
I've just tested it locally. Looks good.

**Review by Mrkisha — APPROVED** [review]

**Comment by Mrkisha** [comment]
@palicao Please tag and release.

**Comment by palicao** [comment]
done! 1.1.1

**Pull request merged**
